[package]
name = "rs-bkstring"
version = "0.1.0"
authors = ["Brian Mackintosh <bcmackintosh@gmail.com>",
           "Mark E. Haase <mehaase@gmail.com>"]

[lib]
name = "bktree"
crate-type = ["dylib"]

[dependencies]
cpython = { git = "https://github.com/dgrunwald/rust-cpython.git" }
rand = "*"
